"use client";

// ============================================================================
// bizdev —— 素材库(MaterialLibrary)数据（宗旨 v21，自动生成）
// ----------------------------------------------------------------------------
// 由 scripts/gen-oceanleo-template-materials.mjs 生成：素材 = asset.oceanleo.com 的**可打开成品
// 模板**（design 编辑器深链，放大态 iframe 预览 + 套用）+ 可选真实图片（如数据图表）。
// 按 app 输出类型选物料：文档站→文档/简历/书封模板，设计站→海报/名片，数据站→图表。
// 分类（顶部 chips）：商务名片 / 商务海报 / 企业展板 / 二维码 / 商务邀请
// ============================================================================

import type { MaterialItem } from "@oceanleo/ui/shell";

export const MATERIALS: MaterialItem[] = [
  { id: "tpl-mc-namecard-01", title: "陈嘉树", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-01.webp?v=202607040933", categories: ["商务名片"], desc: "商务名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-02", title: "李思远", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-02.webp?v=202607040933", categories: ["商务名片"], desc: "商务名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-03", title: "王泊宁", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-03.webp?v=202607040933", categories: ["商务名片"], desc: "商务名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-04", title: "赵明轩", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-04.webp?v=202607040933", categories: ["商务名片"], desc: "商务名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-04.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-05", title: "孙婉清", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-05.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-05.webp?v=202607040933", categories: ["商务名片"], desc: "商务名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-05.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-edu-recruit-teacher", title: "教师招募", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-recruit-teacher.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-recruit-teacher.webp?v=202607040933", categories: ["商务海报"], desc: "商务海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fedu-recruit-teacher.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-edu-promo-class", title: "暑期班抢先报名", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-promo-class.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-promo-class.webp?v=202607040933", categories: ["商务海报"], desc: "商务海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fedu-promo-class.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-edu-quote-study", title: "今天的努力是明天的底气", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-quote-study.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-quote-study.webp?v=202607040933", categories: ["商务海报"], desc: "商务海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fedu-quote-study.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-retail-promo-midyear", title: "年中大促全场狂欢", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-promo-midyear.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-promo-midyear.webp?v=202607040933", categories: ["商务海报"], desc: "商务海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fretail-promo-midyear.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-retail-coupon-newstore", title: "满199减50", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-coupon-newstore.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-coupon-newstore.webp?v=202607040933", categories: ["商务海报"], desc: "商务海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fretail-coupon-newstore.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-board-01", title: "同心致远", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-01.webp?v=202607040933", categories: ["企业展板"], desc: "企业展板 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-board-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-board-02", title: "荣耀时刻", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-02.webp?v=202607040933", categories: ["企业展板"], desc: "企业展板 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-board-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-board-03", title: "年度盛典", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-03.webp?v=202607040933", categories: ["企业展板"], desc: "企业展板 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-board-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-board-04", title: "安全第一", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-board-04.webp?v=202607040933", categories: ["企业展板"], desc: "企业展板 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-board-04.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-qr-01", title: "扫码关注领取福利", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-01.webp?v=202607040933", categories: ["二维码"], desc: "二维码 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-qr-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-qr-02", title: "关注公众号不迷路", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-02.webp?v=202607040933", categories: ["二维码"], desc: "二维码 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-qr-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-qr-03", title: "扫码进入资料库", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-03.webp?v=202607040933", categories: ["二维码"], desc: "二维码 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-qr-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-qr-04", title: "关注官微知民生", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-qr-04.webp?v=202607040933", categories: ["二维码"], desc: "二维码 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-qr-04.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-invite-01", title: "婚礼请柬", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-invite-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-invite-01.webp?v=202607040933", categories: ["商务邀请"], desc: "商务邀请 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-invite-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-invite-02", title: "我们结婚啦", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-invite-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-invite-02.webp?v=202607040933", categories: ["商务邀请"], desc: "商务邀请 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-invite-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-invite-03", title: "答谢晚宴", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-invite-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-invite-03.webp?v=202607040933", categories: ["商务邀请"], desc: "商务邀请 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-invite-03.json", openLabel: "套用此模板", kind: "web" },
];

/** 某成品 app 的素材（默认全量；站点可按 app.id 细分后覆写本函数）。 */
export function materialsForApp(_id: string): MaterialItem[] {
  return MATERIALS;
}
